### ISSUE TITLE
Troubles cloning this repo

### ISSUE THREAD

**Issue by valkyrienyanko** [FaDaQ/Godot-Physics-Objects-Sandbox#1]
There is a filename from the `.godot` folder that is too long preventing me from cloning.

You are not suppose to commit the `.godot` folder. You should remove it from the repo and add `.godot/` to the `.gitignore`

![Untitled](https://user-images.githubusercontent.com/6277739/235368566-9d62e252-7493-47b3-a393-0a4166f3f6e7.png)

**Comment by FaDaQ** [comment]
> There is a filename from the `.godot` folder that is too long preventing me from cloning.
> 
> You are not suppose to commit the `.godot` folder. You should remove it from the repo and add `.godot/` to the `.gitignore`
> 
> ![Untitled](https://user-images.githubusercontent.com/6277739/235368566-9d62e252-7493-47b3-a393-0a4166f3f6e7.png)

Yes, thank you for pointing this out. I'll try to fix it.

I'm just learning to use GitHub (as well as programming), and in general this is my first project that I uploaded here manually, and not through the same Visual Studio, for example.
